# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62b03c0eeab920901946b8d13dcbbf7e0a5d0cf6f22733bc77bfa41b617a8575e84072bcd5d98b551ffb81941c1164ae129e308899a49bcea1f784ec912e1a4

test:
  secret_key_base: d6e3f88bbe1ba68edc05f57f4452273f1bc2d68f9d296b318354d27592c94b7493101270c0b7ed978655ec93e921aa60901782c04f979d935b57b80f06bdfc8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
